/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.librarymgt.View;

import lk.ijse.librarymgt.controller.BooksController;
import lk.ijse.librarymgt.dto.BooksDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.librarymgt.controller.AutherController;
import lk.ijse.librarymgt.dto.AutherDTO;

/**
 *
 * @author Ravindu
 */
public class Bookform extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    /**
     * Creates new form Bookform
     */
    public Bookform() {
        initComponents();
        dtm = (DefaultTableModel) tbl_books.getModel();
        getAllBooks();
        setBookID();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_addbook = new javax.swing.JButton();
        btn_updatebook = new javax.swing.JButton();
        btn_deletebook = new javax.swing.JButton();
        btn_refreshbook = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_catogory = new javax.swing.JTextField();
        txt_bookname = new javax.swing.JTextField();
        txt_bookid = new javax.swing.JTextField();
        txt_isbn = new javax.swing.JTextField();
        txt_publisher = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_autherid = new javax.swing.JTextField();
        txt_publisherid = new javax.swing.JTextField();
        cmbAuther = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_books = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 228, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Form");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/librarymgt/img/icons8_Literature_100px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 110));

        btn_back.setBackground(new java.awt.Color(153, 153, 255));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 760, 200, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addbook.setBackground(new java.awt.Color(51, 153, 0));
        btn_addbook.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_addbook.setText("ADD BOOK");
        btn_addbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addbookActionPerformed(evt);
            }
        });
        jPanel3.add(btn_addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 50));

        btn_updatebook.setBackground(new java.awt.Color(51, 51, 255));
        btn_updatebook.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_updatebook.setText("UPDATE BOOK");
        btn_updatebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_updatebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatebookActionPerformed(evt);
            }
        });
        jPanel3.add(btn_updatebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 50));

        btn_deletebook.setBackground(new java.awt.Color(255, 0, 0));
        btn_deletebook.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_deletebook.setText("DELETE BOOK");
        btn_deletebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_deletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletebookActionPerformed(evt);
            }
        });
        jPanel3.add(btn_deletebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 50));

        btn_refreshbook.setBackground(new java.awt.Color(255, 255, 51));
        btn_refreshbook.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_refreshbook.setText("REFRESH BOOK");
        btn_refreshbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_refreshbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshbookActionPerformed(evt);
            }
        });
        jPanel3.add(btn_refreshbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 180, 190, 460));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Publisher ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Auther");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("ISBN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Book ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Publisher");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 130, 40));

        txt_catogory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_catogory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_catogory, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 280, 30));

        txt_bookname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_bookname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 280, 30));

        txt_bookid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_bookid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 280, 30));

        txt_isbn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_isbn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });
        jPanel2.add(txt_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 280, 30));

        txt_publisher.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_publisher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 280, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Catogory");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 140, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Auther ID");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 130, 40));

        txt_autherid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_autherid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txt_autherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 280, 30));

        txt_publisherid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_publisherid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_publisherid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_publisheridActionPerformed(evt);
            }
        });
        jPanel2.add(txt_publisherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 230, 30));

        cmbAuther.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAutherItemStateChanged(evt);
            }
        });
        cmbAuther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutherActionPerformed(evt);
            }
        });
        jPanel2.add(cmbAuther, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("+");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 20, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("+");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 20, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 1130, 300));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Book ID", "Auther", "Auther ID", "ISBN", "Publisher", "Publisher ID", "Catogory"
            }
        ));
        jScrollPane1.setViewportView(tbl_books);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1070, 90));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 1130, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    private void txt_publisheridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_publisheridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_publisheridActionPerformed

    private void btn_addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addbookActionPerformed
        try {
            String BookID = txt_bookid.getText();
            String BookName = txt_bookname.getText();
//            String Auther = txt_auther.getText();
            String AID = txt_autherid.getText();
            String Isbn = txt_isbn.getText();
            String Publisher = txt_publisher.getText();
            String PID = txt_publisherid.getText();
            String Catogory = txt_catogory.getText();

            BooksDTO bookModel = new BooksDTO(BookID, BookName, AID, Isbn, Publisher, PID, Catogory);
            boolean addBooks = BooksController.addBooks(bookModel);
            if (addBooks) {
                clearAll();
                getAllBooks();
                JOptionPane.showMessageDialog(this, "Added");
            } else {
                JOptionPane.showMessageDialog(this, "Not Added");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addbookActionPerformed

    private void btn_updatebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatebookActionPerformed
        try {
            String BookID = txt_bookid.getText();
            String BookName = txt_bookname.getText();
//            String Auther = txt_auther.getText();
            String AID = txt_autherid.getText();
            String Isbn = txt_isbn.getText();
            String Publisher = txt_publisher.getText();
            String PID = txt_publisherid.getText();
            String Catogory = txt_catogory.getText();

            BooksDTO bookModel = new BooksDTO(BookID, BookName, AID, Isbn, Publisher, PID, Catogory);
            boolean updateBooks = BooksController.updateBooks(bookModel);
            if (updateBooks) {
                clearAll();
                getAllBooks();
                JOptionPane.showMessageDialog(this, "Updated");
            } else {
                JOptionPane.showMessageDialog(this, "Not Updated");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_updatebookActionPerformed

    private void btn_deletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletebookActionPerformed
        try {
            String BookID = txt_bookid.getText();
            boolean deleteBooks = BooksController.deleteBooks(BookID);

            if (deleteBooks) {
                clearAll();
                getAllBooks();
                JOptionPane.showMessageDialog(this, "Deleted");
            } else {
                JOptionPane.showMessageDialog(this, "Not Deleted");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deletebookActionPerformed

    private void btn_refreshbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshbookActionPerformed
        clearAll();
        getAllBooks();
    }//GEN-LAST:event_btn_refreshbookActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void cmbAutherItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAutherItemStateChanged
        try {
            String autherID = cmbAuther.getSelectedItem().toString();
            AutherDTO searchAuther = AutherController.searchAuther(autherID);
            txt_autherid.setText(searchAuther.getAID());

        } catch (SQLException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bookform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbAutherItemStateChanged

    private void cmbAutherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutherActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new Publisherform().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addbook;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_deletebook;
    private javax.swing.JButton btn_refreshbook;
    private javax.swing.JButton btn_updatebook;
    private javax.swing.JComboBox cmbAuther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_books;
    private javax.swing.JTextField txt_autherid;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_bookname;
    private javax.swing.JTextField txt_catogory;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_publisher;
    private javax.swing.JTextField txt_publisherid;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txt_bookid.setText("");
        txt_bookname.setText("");
//        txt_auther.setText("");
        txt_autherid.setText("");
        txt_isbn.setText("");
        txt_publisher.setText("");
        txt_publisherid.setText("");
        txt_catogory.setText("");
        txt_bookid.requestFocus();

    }

    private void getAllBooks() {
        try {

            dtm.setRowCount(0);
            ArrayList<BooksDTO> allBooks = BooksController.getAllBooks();
            for (BooksDTO cus : allBooks) {
                Object[] rowData = {cus.getBname(), cus.getBID(), cus.getAID(), cus.getIsbn(), cus.getPublisher(), cus.getPID(), cus.getCatogory()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customerform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customerform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean deleteBooks(String BookID) throws ClassNotFoundException, SQLException {
        return BooksController.deleteBooks(BookID);
    }

    private void setBookID() {
        int id = new Random().nextInt(9999);
        String prefix = "B0";
        txt_bookid.setText(prefix + id);
    }

    private void loadAllCustomers() {
        cmbAuther.removeAll();
        try {
            ArrayList<AutherDTO> allAuthers = AutherController.getAllAuther();
            for (AutherDTO c : allAuthers) {
                cmbAuther.addItem(c.getAname());
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
